In [1]:
# playing with pandas
import pandas as pd

In [2]:
# Here i created a dataframe  named "data" which consist of  cars and bike 
car={
    "cars":["BMW","Audi","Benz"],
    "bike":["hero","yamaha","aether"]
}
Data=pd.DataFrame(car,index=[1,2,3])
print(Data)

   cars    bike
1   BMW    hero
2  Audi  yamaha
3  Benz  aether

In [3]:
# creating series
series=pd.Series(car)
print(series)

cars         [BMW, Audi, Benz]
bike    [hero, yamaha, aether]
dtype: object

In [29]:
#ASSECESSING index elements
print(series[1])

['hero', 'yamaha', 'aether']

C:\Users\Arcite\AppData\Local\Temp\ipykernel_10968\2777559144.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[1])

In [30]:
#creating a new series
a=[1,2,3,4,5]
ser=pd.Series(a)
print(ser)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [31]:
print(ser.loc[[1,2]])

1    2
2    3
dtype: int64

In [32]:
#import a csv and mentioned i only need 5 rows
df=pd.read_csv(r"C:\Users\Arcite\Downloads\titanic.csv",nrows=5)

In [33]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [34]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [35]:
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [36]:
#converting to csv file
Data.to_csv("Data",index=False)
print(Data)

   cars    bike
1   BMW    hero
2  Audi  yamaha
3  Benz  aether

In [37]:
#read a csv file
import pandas as pd
b=pd.read_csv("Data")
print(b)

   cars    bike
0   BMW    hero
1  Audi  yamaha
2  Benz  aether

In [38]:
# to get the information
print(b.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cars    3 non-null      object
 1   bike    3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes
None

In [39]:
#just printing the dataframe
b

   cars    bike
0   BMW    hero
1  Audi  yamaha
2  Benz  aether

In [40]:
# used to find the count etc here mean and median will be calculated but in this cenario their is no interger value
b.describe()

       cars  bike
count     3     3
unique    3     3
top     BMW  hero
freq      1     1

In [41]:
b.iloc[1:]

   cars    bike
1  Audi  yamaha
2  Benz  aether

In [42]:
import pandas as pd 
grade=[1,2,3]
#new colunm is created

In [43]:
#added grade column to the dataframe
b["grade"]=pd.DataFrame(grade,index=[0,1,2])
print(b)

   cars    bike  grade
0   BMW    hero      1
1  Audi  yamaha      2
2  Benz  aether      3

In [44]:
b["grade"]=pd.Series(grade,index=[0,1,2])
print(b)

   cars    bike  grade
0   BMW    hero      1
1  Audi  yamaha      2
2  Benz  aether      3

In [45]:
#here we find the grade<3 and its mean
b[b["grade"]<3].grade.mean()

np.float64(1.5)

In [46]:
#here to slice the row and columns
b.iloc[1:,1:]

     bike  grade
1  yamaha      2
2  aether      3

In [55]:
#adding one moe column 
rs=[10000,200000,30000]
b["rs"]=pd.DataFrame(rs,index=[0,1,2])
print(b)

   cars    bike  grade      rs
0   BMW    hero      1   10000
1  Audi  yamaha      2  200000
2  Benz  aether      3   30000

In [56]:
#group data in the first level of index
b.groupby(level=0).groups

{0: [0], 1: [1], 2: [2]}

In [ ]:
#data frames problems

In [71]:
list1=[4,2,3,1,5]
ser=pd.Series(list1,index=[5,2,3,4,1])
print(ser)
print("SORT VALUES",ser.sort_values())
print("SORT INDEX",ser.sort_values())

5    4
2    2
3    3
4    1
1    5
dtype: int64
SORT VALUES 4    1
2    2
3    3
5    4
1    5
dtype: int64
SORT INDEX 4    1
2    2
3    3
5    4
1    5
dtype: int64

In [69]:
import pandas as pd

s = pd.Series([20, 10, 40], index=['b', 'a', 'c'])


s_sorted_values = s.sort_values()
print("Sorted by values:\n", s_sorted_values)


s_sorted_index = s.sort_index()
print("Sorted by index:\n", s_sorted_index)

Sorted by values:
 a    10
b    20
c    40
dtype: int64
Sorted by index:
 a    10
b    20
c    40
dtype: int64

In [70]:
import pandas as pd

s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

# Filter: keep values > 20
filtered = s[s > 20]
print(filtered)

c    30
d    40
dtype: int64

In [78]:
print(b)

   cars    bike  grade      rs
0   BMW    hero      1   10000
1  Audi  yamaha      2  200000
2  Benz  aether      3   30000

In [3]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['NY', 'LA', 'NY', 'Chicago'],
    'Salary': [70000, 80000, 120000, 90000]
}

df = pd.DataFrame(data)
print(df)

      Name  Age     City  Salary
0    Alice   25       NY   70000
1      Bob   30       LA   80000
2  Charlie   35       NY  120000
3    David   40  Chicago   90000

In [87]:
#data maunuplations

In [5]:
df[df["Age"]>30].Age.mean()

37.5

In [7]:
df.loc[df['City'] == 'NY', ['Name', 'Salary']]

      Name  Salary
0    Alice   70000
2  Charlie  120000

In [9]:
# Inspecting Data
df.head(2)

    Name  Age City  Salary
0  Alice   25   NY   70000
1    Bob   30   LA   80000

In [11]:
df.tail(2)

      Name  Age     City  Salary
2  Charlie   35       NY  120000
3    David   40  Chicago   90000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Salary  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [15]:
df.describe()

             Age         Salary
count   4.000000       4.000000
mean   32.500000   90000.000000
std     6.454972   21602.468995
min    25.000000   70000.000000
25%    28.750000   77500.000000
50%    32.500000   85000.000000
75%    36.250000   97500.000000
max    40.000000  120000.000000

In [17]:

df

      Name  Age     City  Salary
0    Alice   25       NY   70000
1      Bob   30       LA   80000
2  Charlie   35       NY  120000
3    David   40  Chicago   90000

In [19]:
#3. Selecting Data
df["Name"]

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [27]:
df[["City","Salary"]]

      City  Salary
0       NY   70000
1       LA   80000
2       NY  120000
3  Chicago   90000

In [33]:
df.loc[0,"Name"]#name based indexing

'Alice'

In [41]:
df.iloc[0,3]

70000

In [ ]:
#filtering data

In [45]:
df[df["Salary"]>50000]

      Name  Age     City  Salary
0    Alice   25       NY   70000
1      Bob   30       LA   80000
2  Charlie   35       NY  120000
3    David   40  Chicago   90000

In [47]:
df[(df["Salary"]>50000)& (df["Age"]>30)]

      Name  Age     City  Salary
2  Charlie   35       NY  120000
3    David   40  Chicago   90000

In [ ]:
#Sorting Data

In [51]:
df.sort_values(by='Name', ascending=False)

      Name  Age     City  Salary
3    David   40  Chicago   90000
2  Charlie   35       NY  120000
1      Bob   30       LA   80000
0    Alice   25       NY   70000

In [59]:
df.sort_values(by="Age")

      Name  Age     City  Salary
0    Alice   25       NY   70000
1      Bob   30       LA   80000
2  Charlie   35       NY  120000
3    David   40  Chicago   90000

In [ ]:
#Modifying Data

In [61]:
df.rename(columns={'Salary': 'LPA'})

      Name  Age     City     LPA
0    Alice   25       NY   70000
1      Bob   30       LA   80000
2  Charlie   35       NY  120000
3    David   40  Chicago   90000

In [69]:
df.rename(columns={"City":"Location"})

      Name  Age Location  Salary
0    Alice   25       NY   70000
1      Bob   30       LA   80000
2  Charlie   35       NY  120000
3    David   40  Chicago   90000

In [72]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Department': ['HR', 'IT', 'HR', 'Finance', 'IT', 'Finance'],
    'Salary': [50000, 60000, 52000, 58000, 61000, 57000],
    'Age': [25, 30, 28, 35, 29, 40]
}

df = pd.DataFrame(data)
df

      Name Department  Salary  Age
0    Alice         HR   50000   25
1      Bob         IT   60000   30
2  Charlie         HR   52000   28
3    David    Finance   58000   35
4      Eve         IT   61000   29
5    Frank    Finance   57000   40

In [74]:
df["Salary"].sum()

338000

In [12]:
high_salary = df[df['Salary'] > 55000]
print("\nEmployees with salary > 55000:")
print(high_salary)

Employees with salary > 55000:
    Name Department  Salary  Age
1    Bob         IT   60000   30
3  David    Finance   58000   35
4    Eve         IT   61000   29
5  Frank    Finance   57000   40

In [28]:
group=df.groupby('Department')["Salary"].mean()
print(group)

Department
Finance    57500.0
HR         51000.0
IT         60500.0
Name: Salary, dtype: float64

In [7]:
df = pd.read_csv(r"C:\Users\anant\Desktop\students.csv")
df

      Name  Age  Class
0    Alice   21     10
1      Bob   19     18
2  Charlie   21     12
3    David   12     20
4      Eve   22     12

In [9]:
average_age=df["Age"].mean()
print(average_age)

19.0

In [11]:
max_val=df["Age"].max()
print(max_val)

22

In [56]:
min_val=df["Age"].min()
print(min_val)

12

In [62]:

def sort_dataframe(df):
     return df.sort_values(by=df.columns.tolist(), ascending=True)


# Sample DataFrame
data = {
    'Name': ['David', 'Alice', 'Charlie'],
    'Age': [25, 22, 23]
}

df = pd.DataFrame(data)

# Call the function
sorted_df = sort_dataframe(df)

# Display the sorted DataFrame
print(sorted_df)

      Name  Age
1    Alice   22
2  Charlie   23
0    David   25

In [13]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 17, 40, 22]
}

df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   17
3    David   40
4      Eva   22

In [19]:
df[df["Age"]>25]

    Name  Age
1    Bob   30
3  David   40

In [54]:

data = {
    'Item': ['Pen', 'Notebook', 'Eraser'],
    'Quantity': [10, 5, 3],
    'Price': [5, 20, 2]
}

df = pd.DataFrame(data)
df

       Item  Quantity  Price
0       Pen        10      5
1  Notebook         5     20
2    Eraser         3      2

In [50]:
def totalColumn(df):
    df["Total"]=df["Quantity"]*df["Price"]
    return df

In [52]:

df=totalColumn(df)
print(df)

       Item  Quantity  Price  Total
0       Pen        10      5     50
1  Notebook         5     20    100
2    Eraser         3      2      6