In [3]:
# Data Structures
#Series
#data frame
# https://pandas.pydata.org/

A fast and efficient **DataFrame object for data manipulation with integrated indexing;**

Tools for **reading and writing** data between in-memory data structures and different formats: CSV and text files, Microsoft Excel, SQL databases, and the fast HDF5 format;

Flexible **reshaping and pivoting** of data sets;

Intelligent label-based **slicing, fancy indexing, and subsetting ** of large data sets;

Columns can be **inserted and deleted** from data structures for size mutability;

High performance **merging and joining** of data sets

**Time series-functionality**: date range generation and frequency conversion, moving window statistics, date shifting and lagging. Even create domain-specific time offsets and join time series without losing data;



Application:
use in a wide variety of academic and **commercial domains, including Finance, Neuroscience, Economics, Statistics, Advertising, Web Analytics**, and more.

In [6]:
import pandas as pd

In [7]:
#crete series from list
list1=[1,2,3,4,5]
series_list= pd.Series(list1)
print(series_list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
#crete series from ndarray

series= pd.Series([1,2,3,4,5])
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
#crete series from dict

In [10]:
#crete series from scalar

In [11]:
#accesing elements in series
series[4]

5

In [12]:
#vectorized operation in series

series + series_list

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [13]:
#Data frame

**class pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)**

Two-dimensional, size-mutable, potentially heterogeneous
tabular data.

Data structure also contains labeled axes (rows and columns). Arithmetic operations align on both row and column labels.
>> contain same data type
>> input as list, ndarray, dict, scalar
>> data is in labed form index based along x-axis and y-axis

In [37]:
#create a dataframe from list

import pandas as pd
data = {"number":[1,2,3,4,5],"name":['a','d','f','p','h']}
df = pd.DataFrame(data,index=[1,2,3,4,5],dtype=str)
df

  number name
1      1    a
2      2    d
3      3    f
4      4    p
5      5    h

In [39]:
#create a dataframe from dict

data1={
       0:{"number":1,"name":'a'},
       1:{"number":2,"name":'b'},
       2:{"number":3,"name":'c'},
       3:{"number":4,"name":'d'},
       4:{"number":5,"name":'e'}
}

df1=pd.DataFrame.from_dict(data1)
print(df1)

        0  1  2  3  4
number  1  2  3  4  5
name    a  b  c  d  e

In [17]:
data = {
    0: {'Name': 'Alice', 'Age': 25},
    1: {'Name': 'Bob', 'Age': 30},
    2: {'Name': 'Charlie', 'Age': 35}
}

df = pd.DataFrame.from_dict(data, orient='index')
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [18]:
#create a dataframe from series

olimpyc_participation=pd.Series([205,204,201,200,197],index=[2012,2008,2004,2000,1996])
olimpyc_country=pd.Series(['london','beijing','athens','sydney','athens'],index=[2012,2008,2004,2000,1996])
df3=pd.DataFrame({'olimpyc_participation':olimpyc_participation,'olimpyc_country':olimpyc_country})

In [19]:
print(df3)

      olimpyc_participation olimpyc_country
2012                    205          london
2008                    204         beijing
2004                    201          athens
2000                    200          sydney
1996                    197          athens

In [20]:

#view dataframe
df3.olimpyc_country

2012     london
2008    beijing
2004     athens
2000     sydney
1996     athens
Name: olimpyc_country, dtype: object

In [21]:
# attributes in  dataframe.

In [22]:
df3.shape

(5, 2)

In [23]:
df3.dtypes

olimpyc_participation     int64
olimpyc_country          object
dtype: object

In [24]:
df3.index

Index([2012, 2008, 2004, 2000, 1996], dtype='int64')

In [25]:
df3.columns

Index(['olimpyc_participation', 'olimpyc_country'], dtype='object')

# Summary and Aggregation

Functions	Description
count()	Number of non-null observations
sum()	Sum of values
mean()	Mean of Values
median()	Median of Values
min()	Minimum Value
max()	Maximum Value

In [27]:
df3.head(3)

      olimpyc_participation olimpyc_country
2012                    205          london
2008                    204         beijing
2004                    201          athens

In [28]:
df3.tail(3)

      olimpyc_participation olimpyc_country
2004                    201          athens
2000                    200          sydney
1996                    197          athens

In [29]:
df3.describe()

       olimpyc_participation
count               5.000000
mean              201.400000
std                 3.209361
min               197.000000
25%               200.000000
50%               201.000000
75%               204.000000
max               205.000000

In [30]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 2012 to 1996
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   olimpyc_participation  5 non-null      int64
 1   olimpyc_country        5 non-null      object
dtypes: int64(1), object(1)
memory usage: 120.0+ bytes

In [31]:
df3.count()

olimpyc_participation    5
olimpyc_country          5
dtype: int64

In [32]:
df3["olimpyc_participation"].sum()

1007

In [33]:
df3["olimpyc_participation"]

2012    205
2008    204
2004    201
2000    200
1996    197
Name: olimpyc_participation, dtype: int64

In [34]:
df3[df3["olimpyc_participation"]>=204]

      olimpyc_participation olimpyc_country
2012                    205          london
2008                    204         beijing

In [35]:
df3.groupby(["olimpyc_country"]).sum()

                 olimpyc_participation
olimpyc_country
athens                             398
beijing                            204
london                             205
sydney                             200

In [36]:
df3.groupby("olimpyc_country").filter(lambda x:x["olimpyc_participation"]>=204).any()

TypeError: filter function returned a Series, but expected a scalar bool

In [ ]:
>>> df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
...                               'Parrot', 'Parrot'],
...                    'Max Speed': [380., 370., 24., 26.]})
>>> df
   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0
>>> df.groupby(['Animal']).mean()
        Max Speed
Animal
Falcon      375.0
Parrot       25.0

Merge, join, concatenate and compare

In [ ]:
frames = [df1.T, df]

result = pd.concat(frames)

result